// Generated by CoffeeScript 1.6.3
define(['jquery', 'handlebars', 'turn'], function($, handlebars, turn) {
  var StartApp;
  return StartApp = (function() {
    function StartApp() {
      this.initialize();
    }

    StartApp.prototype.initialize = function() {
      $("#flipbook").trun({
        width: 600,
        height: 400,
        autoCenter: true
      });
      return alert(true);
    };

    return StartApp;

  })();
});
