// Generated by CoffeeScript 1.6.3
define(['jquery', 'handlebars', 'turn'], function($, handlebars, turn) {
  var StartApp;
  return StartApp = (function() {
    function StartApp() {}

    StartApp.prototype.contructor = function() {
      return this.initialize();
    };

    StartApp.prototype.initialize = function() {
      return alert(true);
    };

    return StartApp;

  })();
});
